
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildpack-admission
  labels:
    name: buildpack-admission
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: buildpack-admission
  template:
    metadata:
      name: buildpack-admission
      labels:
        name: buildpack-admission
    spec:
      containers:
        - name: webhook
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "DEBUG"
              value: "{{ .Values.config.debug }}"
            - name: "ALLOWEDDOMAINS"
              value: "{{ .Values.config.harborDomains | join ", " }}"
            - name: "SYSTEMUSERS"
              value: "{{ .Values.config.systemusers | join ", " }}"
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.webhook.secretName }}
