
apiVersion: v1
kind: Service
metadata:
  name: buildpack-admission
  labels:
    name: buildpack-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: buildpack-admission
