apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: buildpack-admission
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ .Values.webhook.secretName }}"
webhooks:
  - name: buildpack-admission.tools.wmcloud.org
    clientConfig:
      caBundle: ""  # injected by cert-manager
      service:
        name: buildpack-admission
        namespace: {{ .Release.Namespace }}
        path: "/"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["tekton.dev"]
        apiVersions: ["v1beta1"]
        resources: ["pipelineruns"]
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    admissionReviewVersions: ["v1"]
    matchPolicy: Equivalent
